export const CHARACTERISTICS_BY_TYPE = {
  ru: [
    "Id",
    "URL-код (slug)",
    "Артикул (SKU)",
    "Название",
    "Бренд",
    "Тип товара",
    "Обычная цена",
    "Цена со скидкой",
    "Технология фильтрации",
    "Количество ступеней",
    "Производительность (л/сутки)",
    "Объем кувшина (л)",
    "Ресурс (литры)",
    "Ресурс (месяцы)",
    "Тонкость фильтрации (мкм)",
    "Мембрана (GPD)",
    "Объем бака (л)",
    "Скорость потока (л/мин)",
    "Размер подключения (дюймы)",
    "Рабочее давление (мин.)",
    "Рабочее давление (макс.)",
    "Рабочая температура (мин.)",
    "Рабочая температура (макс.)",
    "Сертификация",
    "Габариты (мм)",
    "Габариты бака (мм)",
    "Вес (кг)",
    "Размер упаковки (мм)",
    "Вес с упаковкой (кг)",
    "Комплектация",
    "Совместимые модели",
    "Гарантия (мес.)",
    "Страна производства",
  ],
  ro: [
    "Id",
    "Cod URL (slug)",
    "Cod produs (SKU)",
    "Denumire",
    "Brand",
    "Tip produs",
    "Preț obișnuit",
    "Preț redus",
    "Tehnologie de filtrare",
    "Număr de trepte",
    "Capacitate (l/zi)",
    "Volum cană (l)",
    "Durată de viață (litri)",
    "Durată de viață (luni)",
    "Grad de filtrare (microni)",
    "Membrană (GPD)",
    "Volum rezervor (l)",
    "Debit (l/min)",
    "Dimensiune racord (inch)",
    "Presiune minimă (bar)",
    "Presiune maximă (bar)",
    "Temperatura minimă (°C)",
    "Temperatura maximă (°C)",
    "Certificare",
    "Dimensiuni (mm)",
    "Dimensiuni rezervor (mm)",
    "Greutate (kg)",
    "Dimensiuni ambalaj (mm)",
    "Greutate cu ambalaj (kg)",
    "Pachet complet",
    "Modele compatibile",
    "Garanție (luni)",
    "Țara de origine",
  ],
};

export const EDIT_CHARACTERISTICS_BY_TYPE = {
  'Кувшины': [
    'Тип фильтрации',
    'Материал',
    'Применение',
    'Объем кувшина',
    'Ресурс фильтра',
    'Температура воды',
    'Скорость фильтрации',
  ],
  'Carafe': [
    'Tip filtrare',
    'Material',
    'Aplicare',
    'Volum carafă',
    'Durată filtru',
    'Temperatura apei',
    'Viteză de filtrare',
  ],
  'Проточный фильтр': [
    'Тип фильтрации',
    'Материал',
    'Применение',
    'Мин. давление',
    'Макс. давление',
    'Температура воды',
    'Кол-во ступеней очистки',
    'Скорость фильтрации',
    'Тип подключения',
  ],
  'Filtru de trecere': [
    'Tip filtrare',
    'Material',
    'Aplicare',
    'Presiune minimă',
    'Presiune maximă',
    'Temperatura apei',
    'Număr de etape de filtrare',
    'Viteză de filtrare',
    'Tip de conectare',
  ],
  'Обратный осмос': [
    'Тип фильтрации',
    'Пористость',
    'Материал',
    'Применение',
    'Мин. давление',
    'Макс. давление',
    'Температура воды',
    'Кол-во ступеней очистки',
    'Скорость фильтрации',
    'Тип подключения',
  ],
  'Osmoză inversă': [
    'Tip filtrare',
    'Porozitate',
    'Material',
    'Aplicare',
    'Presiune minimă',
    'Presiune maximă',
    'Temperatura apei',
    'Număr de etape de filtrare',
    'Viteză de filtrare',
    'Tip de conectare',
  ],
  'Предфильтр': [
    'Тип фильтрации',
    'Размер',
    'Пористость',
    'Материал',
    'Применение',
    'Мин. давление',
    'Макс. давление',
    'Температура воды',
    'Кол-во ступеней очистки',
    'Скорость фильтрации',
    'Тип подключения',
  ],
  'Prefiltru': [
    'Tip filtrare',
    'Dimensiune',
    'Porozitate',
    'Material',
    'Aplicare',
    'Presiune minimă',
    'Presiune maximă',
    'Temperatura apei',
    'Număr de etape de filtrare',
    'Viteză de filtrare',
    'Tip de conectare',
  ],
}
